name: Deploy cv page

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: shok1122/ruby:3.2.2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build HTML
        run:  ruby ./run.rb
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
