name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    container:
      image: shok1122/ruby:3.2.2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: pwd
      - run: ls -la

