name: learn-github-actions

run-name: ${{ github.actor }} is learning GitHub Actions

on: [push]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: shok1122/ruby:3.2.2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build HTML
        run:  ruby ./run.rb
      - uses: actions/upload-pages-artifact@v4
        with:
          path: ./dist
  #
  # Deployment job
  #
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
